import axios from 'axios';
import Head from 'next/head';
import { useState } from 'react';
import { apiURL, configAPI } from '../../config';
import * as XLSX from 'xlsx';

export default function StoreIntroduce({}) {

  const [HTMLTextTable, setHTMLTextTable] = useState(null);
  const [HTMLTextAns, setHTMLTextAns] = useState(null);

	const handleSubmitFile = async (event) => {
    event.preventDefault();

    const params = {
      file: event.target.file.files[0]
    }

    const fine_tune = await axios.post(`${apiURL}/  fine-tune/create`, params, configAPI);
    // const params = {
    //   "model": "text-davinci-003",
    //   "prompt": `render html table with class=table from ${JSON.stringify(dataSLXS)}`,
    //   "max_tokens": 100,
    //   "temperature": 1
    // }
    // axios.post('https://api.openai.com/v1/completions', params, configAPI).then((res) => {
    //   console.log(res.data.choices[0])
    //   setHTMLTextTable(res.data.choices[0].text);
    // })
    
  }

  const handleSubmitChat =(event) => {
    event.preventDefault();
    const params2 = {
      "model": "curie:ft-personal-2023-01-31-07-50-48",
      "prompt": `${event.target.message.value}`,
      "max_tokens": 260,
      "temperature": 1
    }
    axios.post('https://api.openai.com/v1/completions', params2, configAPI).then((res) => {
      console.log(res.data.choices[0]);
      setHTMLTextAns(res.data.choices[0].text);
    })
  }
  return (
    <>
      <Head>
        <title>Analyze</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/*<form onSubmit={handleSubmitFile}>
          <div className="form-group">
            <label>Choose execel file to analyze</label>
            <input className="form-control mt-2" type="file" name="file"/>
          </div>
          <input className="btn btn-primary mt-2" type="submit"/>
        </form>

        <div className='mt-1' dangerouslySetInnerHTML={{ __html: HTMLTextTable }}/>*/}

      
          <>
            <form onSubmit={handleSubmitChat} className='mt-3'>
              <div className="form-group">
                <label>Message</label>
                <input className="form-control" type="text" name="message" placeholder='Enter message'/>
              </div>
              <input type="submit" className="btn btn-primary mt-2" value='Chat'/>
            </form>
            <div className='mt-1' dangerouslySetInnerHTML={{ __html: HTMLTextAns}}/>
          </>

        
      </main>
    </>);
}

// export const getStaticPaths = async () => {
//   const response = await axios.get("https://api.openai.com/v1/fine-tunes", configAPI);
//   const pathsWithParams = response.data.data.map((item) => ({ params: { id: item.id }}));
//   console.log(response.data.data);
//   return {
//     paths: pathsWithParams,
//     fallback: true,
//   };
// };

export const getStaticProps = async ({params}) => {
	// console.log(params.id);
  // const response = await fetch(`https://api.openai.com/v1/fine-tunes/${params.id}`, configAPI)

  return {
    props: {
      // data: response.data | null
    }
  };
};