import axios from 'axios';
import { GetStaticPaths, GetStaticProps } from 'next';
import Head from 'next/head';

export default function StoreIntroduce({data}) {
  return (
    <>
      <Head>
        <title>Tera Car</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data}
    </>);
}

export const getStaticPaths = async () => {
  const response = axios.get("https://api.openai.com/v1/fine-tunes", configAPI)
  const pathsWithParams = response.data.data.map((item) => ({ params: { id: item.id }}));

  return {
    paths: pathsWithParams,
    fallback: true
  };
};

export const getStaticProps = async ({params}) => {
  const data = axios.get(`https://api.openai.com/v1/fine-tunes/${params.id}`, configAPI)
  return {
    props: {
      data //get data by params.slug
    }
  };
};